import { Router, Request, Response } from 'express';

export const policyRouter = Router();

/**
 * POST /api/policy/download
 * Generates a downloadable policy document as structured text
 */
policyRouter.post('/download', (req: Request, res: Response) => {
  const { policyDocument } = req.body;

  if (!policyDocument || !policyDocument.sections) {
    res.status(400).json({ error: 'Policy document data is required' });
    return;
  }

  const doc = policyDocument;
  const lines: string[] = [];

  lines.push('='.repeat(80));
  lines.push(doc.title.toUpperCase());
  lines.push('='.repeat(80));
  lines.push('');
  lines.push(`Standard:        ${doc.standardName} (${doc.standardCode})`);
  lines.push(`Version:         ${doc.version}`);
  lines.push(`Effective Date:  ${doc.effectiveDate}`);
  lines.push(`Compliance:      ${doc.complianceScore}%`);
  lines.push(`Gaps Addressed:  ${doc.gapsAddressed}`);
  lines.push('');
  lines.push('-'.repeat(80));
  lines.push('EXECUTIVE SUMMARY');
  lines.push('-'.repeat(80));
  lines.push(doc.summary);
  lines.push('');

  for (const section of doc.sections) {
    lines.push('-'.repeat(80));
    lines.push(`${section.sectionNumber}. ${section.title}`);
    lines.push(`   Clause Reference: ${section.clauseRef} | Status: ${section.status.toUpperCase()}`);
    lines.push('-'.repeat(80));
    lines.push(section.content);
    lines.push('');
  }

  lines.push('='.repeat(80));
  lines.push('END OF POLICY DOCUMENT');
  lines.push(`Generated by SentriX Policy Generator Agent`);
  lines.push(`Date: ${new Date().toISOString()}`);
  lines.push('='.repeat(80));

  const content = lines.join('\n');
  const filename = `${doc.standardCode}_Policy_v${doc.version}.txt`;

  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.send(content);
});
