import { Router, Request, Response } from 'express';

export const reportRouter = Router();

reportRouter.post('/generate', (req: Request, res: Response) => {
  const { assessmentResult } = req.body;

  if (!assessmentResult) {
    res.status(400).json({ error: 'Assessment result is required' });
    return;
  }

  // Generate a structured report JSON (PDF generation handled client-side via jsPDF)
  const report = {
    title: 'SentriX™ Assessment Report',
    generatedAt: new Date().toISOString(),
    organization: assessmentResult.orgProfile,
    executiveSummary: {
      overallScore: assessmentResult.overallScore,
      maturityLevel: assessmentResult.maturityLevel,
      standardsAssessed: assessmentResult.standardAssessments?.length || 0,
      gapsIdentified: assessmentResult.gaps?.length || 0,
      criticalGaps: assessmentResult.gaps?.filter((g: { severity: string }) => g.severity === 'critical').length || 0,
      remediationActions: assessmentResult.remediationActions?.length || 0,
    },
    standardAssessments: assessmentResult.standardAssessments,
    gaps: assessmentResult.gaps,
    remediationRoadmap: assessmentResult.remediationActions,
    disclaimer: 'This report was generated by SentriX™ powered by Enterprise Core OmniAgent™. It provides an AI-assisted preliminary assessment and should not replace professional compliance advisory services.',
  };

  res.json(report);
});
