import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { AssessmentResult } from '../types';

function getRiskLabel(score: number): string {
  if (score >= 75) return 'Implemented';
  if (score >= 60) return 'Partial';
  if (score >= 33) return 'Planned';
  return 'Not Started';
}

function getMaturityLabel(level: number): string {
  const labels: Record<number, string> = { 1: 'Initial', 2: 'Defined', 3: 'Managed', 4: 'Quantified', 5: 'Optimizing' };
  return labels[level] || 'Unknown';
}

export function generateReport(assessment: AssessmentResult): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 0;

  // --- Cover Page ---
  doc.setFillColor(10, 14, 26);
  doc.rect(0, 0, pageWidth, 297, 'F');

  // Green accent bar
  doc.setFillColor(0, 195, 137);
  doc.rect(0, 0, 6, 297, 'F');

  // Title
  doc.setTextColor(240, 244, 255);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text('SentriX™', margin + 8, 60);

  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(139, 156, 200);
  doc.text('Threat Intelligence & Vulnerability Report', margin + 8, 75);

  // Organization
  doc.setFontSize(20);
  doc.setTextColor(240, 244, 255);
  doc.setFont('helvetica', 'bold');
  doc.text(assessment.orgProfile.companyName, margin + 8, 110);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(139, 156, 200);
  doc.text(`Industry: ${assessment.orgProfile.industrySector}`, margin + 8, 122);
  doc.text(`Employees: ${assessment.orgProfile.employeeCount}`, margin + 8, 130);
  doc.text(`Date: ${new Date(assessment.timestamp).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin + 8, 138);

  // Score box
  const boxY = 160;
  doc.setFillColor(22, 32, 64);
  doc.roundedRect(margin + 8, boxY, 70, 50, 4, 4, 'F');
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 195, 137);
  doc.text(`${assessment.overallScore}%`, margin + 20, boxY + 28);
  doc.setFontSize(10);
  doc.setTextColor(139, 156, 200);
  doc.text('Overall Score', margin + 20, boxY + 40);

  doc.setFillColor(22, 32, 64);
  doc.roundedRect(margin + 88, boxY, 70, 50, 4, 4, 'F');
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 229, 160);
  doc.text(`L${assessment.overallMaturity}`, margin + 104, boxY + 28);
  doc.setFontSize(10);
  doc.setTextColor(139, 156, 200);
  doc.text(getMaturityLabel(assessment.overallMaturity), margin + 96, boxY + 40);

  // Standards covered
  doc.setFontSize(11);
  doc.setTextColor(139, 156, 200);
  doc.text('Standards Assessed:', margin + 8, 230);
  assessment.standards.forEach((s, i) => {
    doc.setTextColor(0, 195, 137);
    doc.text(`• ${s.standardCode.replace('ISO', 'ISO ')} — ${s.standardName}`, margin + 14, 240 + i * 8);
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(74, 86, 128);
  doc.text('Generated by SentriX™ AI-Powered Compliance Platform', margin + 8, 280);
  doc.text('Confidential — For internal use only', pageWidth - margin - 60, 280);

  // --- Page 2: Executive Summary ---
  doc.addPage();
  doc.setFillColor(10, 14, 26);
  doc.rect(0, 0, pageWidth, 297, 'F');
  doc.setFillColor(0, 195, 137);
  doc.rect(0, 0, 6, 297, 'F');

  y = 30;
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(240, 244, 255);
  doc.text('Executive Summary', margin + 8, y);

  y += 15;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(139, 156, 200);
  const summaryLines = doc.splitTextToSize(assessment.executiveSummary, pageWidth - margin * 2 - 10);
  doc.text(summaryLines, margin + 8, y);
  y += summaryLines.length * 5 + 15;

  // Standards summary table
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(240, 244, 255);
  doc.text('Standards Overview', margin + 8, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [['Standard', 'Score', 'Maturity', 'Clauses Assessed']],
    body: assessment.standards.map((s) => [
      `${s.standardCode.replace('ISO', 'ISO ')}`,
      `${s.overallScore}%`,
      `Level ${s.maturityLevel} — ${s.maturityLabel}`,
      `${s.clauseScores.length}`,
    ]),
    styles: {
      fillColor: [15, 22, 41],
      textColor: [139, 156, 200],
      fontSize: 9,
      cellPadding: 4,
    },
    headStyles: {
      fillColor: [22, 32, 64],
      textColor: [0, 195, 137],
      fontStyle: 'bold',
      fontSize: 9,
    },
    alternateRowStyles: { fillColor: [10, 14, 26] },
    margin: { left: margin + 8, right: margin },
  });

  // --- Per-Standard Detail Pages ---
  for (const standard of assessment.standards) {
    doc.addPage();
    doc.setFillColor(10, 14, 26);
    doc.rect(0, 0, pageWidth, 297, 'F');
    doc.setFillColor(0, 195, 137);
    doc.rect(0, 0, 6, 297, 'F');

    y = 30;
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(240, 244, 255);
    doc.text(`${standard.standardCode.replace('ISO', 'ISO ')} — ${standard.standardName}`, margin + 8, y);

    y += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(139, 156, 200);
    doc.text(`Overall Score: ${standard.overallScore}%  |  Maturity: Level ${standard.maturityLevel} (${standard.maturityLabel})`, margin + 8, y);

    y += 8;
    const summLines = doc.splitTextToSize(standard.summary, pageWidth - margin * 2 - 10);
    doc.text(summLines, margin + 8, y);
    y += summLines.length * 5 + 10;

    // Clause scores table
    autoTable(doc, {
      startY: y,
      head: [['Clause', 'Title', 'Score', 'Status', 'Gap']],
      body: standard.clauseScores.map((c) => [
        c.clauseId,
        c.clauseTitle,
        `${c.score}%`,
        getRiskLabel(c.score),
        c.gap || '—',
      ]),
      styles: {
        fillColor: [15, 22, 41],
        textColor: [139, 156, 200],
        fontSize: 8,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: [22, 32, 64],
        textColor: [0, 195, 137],
        fontStyle: 'bold',
        fontSize: 8,
      },
      alternateRowStyles: { fillColor: [10, 14, 26] },
      columnStyles: {
        0: { cellWidth: 18 },
        1: { cellWidth: 40 },
        2: { cellWidth: 18 },
        3: { cellWidth: 22 },
        4: { cellWidth: 'auto' },
      },
      margin: { left: margin + 8, right: margin },
    });
  }

  // --- Gaps Page ---
  doc.addPage();
  doc.setFillColor(10, 14, 26);
  doc.rect(0, 0, pageWidth, 297, 'F');
  doc.setFillColor(0, 195, 137);
  doc.rect(0, 0, 6, 297, 'F');

  y = 30;
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(240, 244, 255);
  doc.text('Gap Analysis', margin + 8, y);

  y += 12;
  autoTable(doc, {
    startY: y,
    head: [['#', 'Gap', 'Standard', 'Severity', 'Impact', 'Effort (days)']],
    body: assessment.gaps.map((g, i) => [
      `${i + 1}`,
      g.title,
      g.standardCode.replace('ISO', 'ISO '),
      g.impact.toUpperCase(),
      `${g.impactScore}/10`,
      `${g.effort}`,
    ]),
    styles: {
      fillColor: [15, 22, 41],
      textColor: [139, 156, 200],
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [22, 32, 64],
      textColor: [0, 195, 137],
      fontStyle: 'bold',
      fontSize: 8,
    },
    alternateRowStyles: { fillColor: [10, 14, 26] },
    margin: { left: margin + 8, right: margin },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 3) {
        const val = String(data.cell.raw).toLowerCase();
        if (val === 'critical') data.cell.styles.textColor = [255, 71, 87];
        else if (val === 'high') data.cell.styles.textColor = [255, 107, 53];
        else if (val === 'medium') data.cell.styles.textColor = [255, 211, 42];
      }
    },
  });

  // --- Remediation Roadmap Page ---
  doc.addPage();
  doc.setFillColor(10, 14, 26);
  doc.rect(0, 0, pageWidth, 297, 'F');
  doc.setFillColor(0, 195, 137);
  doc.rect(0, 0, 6, 297, 'F');

  y = 30;
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(240, 244, 255);
  doc.text('Remediation Roadmap', margin + 8, y);

  for (const phase of [1, 2, 3] as const) {
    const phaseActions = assessment.remediation.filter((r) => r.phase === phase);
    if (phaseActions.length === 0) continue;

    y = (doc as any).lastAutoTable?.finalY + 15 || y + 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 195, 137);
    doc.text(phaseActions[0].phaseLabel, margin + 8, y);
    y += 6;

    autoTable(doc, {
      startY: y,
      head: [['Action', 'Priority', 'Effort', 'Standards', 'Owner']],
      body: phaseActions.map((r) => [
        r.title,
        r.priority.toUpperCase(),
        `${r.effortDays}d`,
        r.standards.join(', '),
        r.responsibleFunction,
      ]),
      styles: {
        fillColor: [15, 22, 41],
        textColor: [139, 156, 200],
        fontSize: 8,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: [22, 32, 64],
        textColor: [0, 195, 137],
        fontStyle: 'bold',
        fontSize: 8,
      },
      alternateRowStyles: { fillColor: [10, 14, 26] },
      margin: { left: margin + 8, right: margin },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 1) {
          const val = String(data.cell.raw).toLowerCase();
          if (val === 'critical') data.cell.styles.textColor = [255, 71, 87];
          else if (val === 'high') data.cell.styles.textColor = [255, 107, 53];
        }
      },
    });
  }

  // Add page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(74, 86, 128);
    doc.text(`Page ${i - 1} of ${totalPages - 1}`, pageWidth - margin - 20, 290);
    doc.text('SentriX™ Report', margin + 8, 290);
  }

  // Save
  const filename = `SentriX_${assessment.orgProfile.companyName.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
